BASE_LLM = "llama-3.3-70b-versatile"
SMALL_LLM = "qwen2.5:3b"
EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
OPENAI_API_BASE = "https://api.groq.com/openai/v1"
OLLAMA_API_BASE = "http://ollama:11434"
